version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/RAGRARIAN
    environment:
      - PYTHONPATH=/RAGRARIAN
    command: uvicorn Rag_app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ..:/RAGRARIAN
    environment:
      - PYTHONPATH=/RAGRARIAN
    command: streamlit run Rag_app/frontend/streamlit.py
    