version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ..:/RAGRARIAN
    environment:
      - PYTHONPATH=/RAGRARIAN
